### ISSUE TITLE
[Jetpack] Jetpack armor appearance should match grounded armor appearance

### ISSUE THREAD

**Issue by AvengerStar** [EarendelDevelopers/factorio-mods#189] opened 2022-03-10 12:03 UTC
Currently, the jetpack character only has graphics for power armor. This is fine in most typical cases, though it is possible to equip jetpacks on modular armor, or, in the case of, say, IR2, light armor. The appearances of armor prior to power armor are not carried over to the jetpack character.

This is not a big deal, considering the amount of time spent with jetpacks on power armor eclipses that spent on prior tiers, but the consistency would be appreciated.

**Comment by Wiwiweb** [comment] 2022-03-10 18:54
I think we'll have to file that one under "Known bug, won't fix".
From Earendel: "It would be possible to have extra sprite sheets for different armour sets, but I don't think it's worth the vram usage to add those."

(Also hi! :D)

**Comment by EarendelGames** [comment] 2022-03-10 22:59
Hi, welcome back.  
Yeah, the problem is that my experiments with trying to use the original character sprites with the jetpack didn't work at all. The character you see with the jetpack had to be scupled from scratch and is stuck in that pose. I don't really want to have to make the other armour states too. Plus people are already complaining that the added graphics load is unsecessary.

**Comment by AvengerStar** [comment] 2022-03-10 23:11
Fair enough, I figured it would've been done already if it wasn't a hassle to do.

**Comment by InappropriatePenguin** [comment] 2022-04-03 16:15
I'll go ahead and close this as a won't-fix for now. It can always be reopened if the situation changes.

Good to see you here, AK :)

**Closed as completed by InappropriatePenguin** 2022-04-03 16:15 UTC
Labels: wontfix, suggestion, jetpack
